// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCUQrodPQ6aMV9DJvFk-SV-AGoMzCEMD4',
    appId: '1:1035193508990:web:6dd43daadff7a764b1242f',
    messagingSenderId: '1035193508990',
    projectId: 'chat-app-94ed1',
    authDomain: 'chat-app-94ed1.firebaseapp.com',
    storageBucket: 'chat-app-94ed1.appspot.com',
    measurementId: 'G-XNNKWJWVW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEV1MKGZMmjgIPiGMTYhvMJoPs9XYiksw',
    appId: '1:1035193508990:android:33f7ce3b6279a23bb1242f',
    messagingSenderId: '1035193508990',
    projectId: 'chat-app-94ed1',
    storageBucket: 'chat-app-94ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSpu6uh9CkTGPMVVWapnHNFKExNP6h6EI',
    appId: '1:1035193508990:ios:1ca11d42507eec1fb1242f',
    messagingSenderId: '1035193508990',
    projectId: 'chat-app-94ed1',
    storageBucket: 'chat-app-94ed1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSpu6uh9CkTGPMVVWapnHNFKExNP6h6EI',
    appId: '1:1035193508990:ios:b22ffc26f5c47135b1242f',
    messagingSenderId: '1035193508990',
    projectId: 'chat-app-94ed1',
    storageBucket: 'chat-app-94ed1.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
